/* ============================================================================
   SCRIPT DDL FIREBIRD PARA VPS LINUX E BANCO LOCAL - LAZARUS PORTABLE MANAGER
   ============================================================================
   Compatível com Firebird 3.0 / 4.0 / 5.0 (Windows / Linux x64)
   Charset recomendado: UTF8
   ============================================================================ */

/* 1. TABELA DE USUÁRIOS */
CREATE TABLE USUARIOS (
    ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    SENHA_HASH VARCHAR(64) NOT NULL,
    HWID VARCHAR(100),
    IS_ADMIN SMALLINT DEFAULT 0 NOT NULL, -- 0 = Usuário Normal, 1 = Administrador Geral
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'ATIVO'
);

CREATE GENERATOR GEN_USUARIOS_ID;
SET GENERATOR GEN_USUARIOS_ID TO 0;

SET TERM ^ ;
CREATE TRIGGER TRG_USUARIOS_BI FOR USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_USUARIOS_ID, 1);
END^
SET TERM ; ^

/* 2. TABELA DE LICENÇAS */
CREATE TABLE LICENCAS (
    ID INTEGER NOT NULL PRIMARY KEY,
    USUARIO_ID INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    TIPO_LICENCA VARCHAR(50) DEFAULT 'TRIAL_10_DIAS', -- 'TRIAL_10_DIAS', 'MENSAL', 'ANUAL', 'VITALICIA'
    DATA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_EXPIRACAO TIMESTAMP NOT NULL,
    STATUS_ATIVO SMALLINT DEFAULT 1
);

CREATE GENERATOR GEN_LICENCAS_ID;
SET GENERATOR GEN_LICENCAS_ID TO 0;

SET TERM ^ ;
CREATE TRIGGER TRG_LICENCAS_BI FOR LICENCAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_LICENCAS_ID, 1);
END^
SET TERM ; ^

/* 3. TABELA DE COMPROVANTES DE PAGAMENTO PIX */
CREATE TABLE COMPROVANTES_PAGAMENTO (
    ID INTEGER NOT NULL PRIMARY KEY,
    USUARIO_ID INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    DATA_ENVIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHAVE_PIX_USADA VARCHAR(250),
    VALOR_PAGO NUMERIC(15,2),
    COMPROVANTE_BLOB BLOB SUB_TYPE 0 SEGMENT SIZE 4096,
    NOME_ARQUIVO VARCHAR(255),
    STATUS_ANALISE VARCHAR(30) DEFAULT 'AGUARDANDO_APROVACAO', -- 'AGUARDANDO_APROVACAO', 'APROVADO', 'REJEITADO'
    OBSERVACAO VARCHAR(255)
);

CREATE GENERATOR GEN_COMPROVANTES_ID;
SET GENERATOR GEN_COMPROVANTES_ID TO 0;

SET TERM ^ ;
CREATE TRIGGER TRG_COMPROVANTES_BI FOR COMPROVANTES_PAGAMENTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_COMPROVANTES_ID, 1);
END^
SET TERM ; ^

/* 4. ÍNDICES DE DESEMPENHO */
CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(EMAIL);
CREATE INDEX IDX_LICENCAS_USUARIO ON LICENCAS(USUARIO_ID, STATUS_ATIVO);
CREATE INDEX IDX_COMPROVANTES_USUARIO ON COMPROVANTES_PAGAMENTO(USUARIO_ID);

/* ============================================================================
   REGISTRO INICIAL DO ADMINISTRADOR GERAL E LICENÇA VITALÍCIA
   E-mail: conectsolutions@hotmail.com
   Senha:  Mmpa@2025
   Hash:   33f30ae417104ebd023ac9c3dccdf4f3dd376c7c
   ============================================================================ */

INSERT INTO USUARIOS (ID, NOME, EMAIL, SENHA_HASH, HWID, IS_ADMIN, STATUS)
VALUES (1, 'Administrador Geral', 'conectsolutions@hotmail.com', '33f30ae417104ebd023ac9c3dccdf4f3dd376c7c', 'ADMIN_MASTER', 1, 'ATIVO');

INSERT INTO LICENCAS (ID, USUARIO_ID, TIPO_LICENCA, DATA_INICIO, DATA_EXPIRACAO, STATUS_ATIVO)
VALUES (1, 1, 'VITALICIA', CURRENT_TIMESTAMP, '2099-12-31 23:59:59', 1);

/* 5. TABELA DE CONFIGURAÇÃO DE PAGAMENTO PIX DO ADMINISTRADOR */
CREATE TABLE CONFIG_PIX (
    ID INTEGER NOT NULL PRIMARY KEY,
    CHAVE_PIX VARCHAR(150) NOT NULL,
    TIPO_CHAVE VARCHAR(50) DEFAULT 'EMAIL', -- 'EMAIL', 'CPF', 'CNPJ', 'TELEFONE', 'ALEATORIA'
    TITULAR VARCHAR(150),
    BANCO VARCHAR(100),
    VALOR_LICENCA NUMERIC(15,2) DEFAULT 49.90,
    INSTRUCOES VARCHAR(500),
    ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO CONFIG_PIX (ID, CHAVE_PIX, TIPO_CHAVE, TITULAR, BANCO, VALOR_LICENCA, INSTRUCOES)
VALUES (1, '5511945457934', 'TELEFONE', 'Administrador Geral', 'C6 Bank', 49.90, 'Após efetuar o PIX, anexe o comprovante na tela de licença para liberação.');

COMMIT;

/* ============================================================================
   SCRIPT MIGRACIONAL PARA BANCOS JÁ EXISTENTES:
   Rode os comandos abaixo no IBExpert / isql caso o banco já tenha sido criado:

   ALTER TABLE USUARIOS ADD IS_ADMIN SMALLINT DEFAULT 0 NOT NULL;
   UPDATE USUARIOS SET IS_ADMIN = 1 WHERE EMAIL = 'conectsolutions@hotmail.com';
   ALTER TABLE COMPROVANTES_PAGAMENTO ALTER COLUMN CHAVE_PIX_USADA TYPE VARCHAR(250);

   CREATE TABLE CONFIG_PIX (
       ID INTEGER NOT NULL PRIMARY KEY,
       CHAVE_PIX VARCHAR(150) NOT NULL,
       TIPO_CHAVE VARCHAR(50) DEFAULT 'TELEFONE',
       TITULAR VARCHAR(150),
       BANCO VARCHAR(100),
       VALOR_LICENCA NUMERIC(15,2) DEFAULT 49.90,
       INSTRUCOES VARCHAR(500),
       ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   );
   INSERT INTO CONFIG_PIX (ID, CHAVE_PIX, TIPO_CHAVE, TITULAR, BANCO, VALOR_LICENCA, INSTRUCOES)
   VALUES (1, '5511945457934', 'TELEFONE', 'Administrador Geral', 'C6 Bank', 49.90, 'Após efetuar o PIX, anexe o comprovante na tela de licença para liberação.');
   COMMIT;
   ============================================================================ */

