/* ============================================================================
   SCRIPT DE MIGRAÇÃO E ATUALIZAÇÃO - BANCOS EXISTENTES FIREBIRD
   ============================================================================
   Execute este script no IBExpert (Script Executive / F12) conectado ao seu banco.
   Compatível com Firebird 2.5 / 3.0 / 4.0 / 5.0.
   ============================================================================ */

SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  /* 1. Adiciona coluna HWID na tabela USUARIOS se não existir */
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS 
    WHERE RDB$RELATION_NAME = 'USUARIOS' AND RDB$FIELD_NAME = 'HWID'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'ALTER TABLE USUARIOS ADD HWID VARCHAR(100);';
  END

  /* 2. Adiciona coluna DATA_CADASTRO na tabela USUARIOS se não existir */
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS 
    WHERE RDB$RELATION_NAME = 'USUARIOS' AND RDB$FIELD_NAME = 'DATA_CADASTRO'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'ALTER TABLE USUARIOS ADD DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP;';
  END

  /* 3. Adiciona coluna STATUS na tabela USUARIOS se não existir */
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS 
    WHERE RDB$RELATION_NAME = 'USUARIOS' AND RDB$FIELD_NAME = 'STATUS'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'ALTER TABLE USUARIOS ADD STATUS VARCHAR(20) DEFAULT ''ATIVO'';';
  END

  /* 4. Adiciona coluna IS_ADMIN na tabela USUARIOS se não existir */
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_FIELDS 
    WHERE RDB$RELATION_NAME = 'USUARIOS' AND RDB$FIELD_NAME = 'IS_ADMIN'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'ALTER TABLE USUARIOS ADD IS_ADMIN SMALLINT DEFAULT 0;';
  END

  /* 5. Garante Índice no HWID para busca rápida anti-fraude */
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_USUARIOS_HWID'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_USUARIOS_HWID ON USUARIOS(HWID);';
  END

  /* 6. Garante Índice no EMAIL */
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_USUARIOS_EMAIL'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(EMAIL);';
  END

  /* 7. Garante Índice nas LICENÇAS */
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_LICENCAS_USUARIO'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_LICENCAS_USUARIO ON LICENCAS(USUARIO_ID, STATUS_ATIVO);';
  END

  /* 8. Garante Índice nos COMPROVANTES */
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_COMPROVANTES_USUARIO'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE INDEX IDX_COMPROVANTES_USUARIO ON COMPROVANTES_PAGAMENTO(USUARIO_ID);';
  END
END^

SET TERM ; ^

/* 9. Marca o Super Administrador Geral */
UPDATE USUARIOS 
SET IS_ADMIN = 1 
WHERE LOWER(EMAIL) = 'conectsolutions@hotmail.com';

COMMIT;
