/* ============================================================================
   SCRIPT DDL FIREBIRD PARA VPS LINUX - LAZARUS PORTABLE MANAGER
   ============================================================================
   Compatível com Firebird 3.0+ / 4.0 / 5.0 (Linux x64)
   ============================================================================ */

/* 1. TABELA DE USUÁRIOS */
CREATE TABLE USUARIOS (
    ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    SENHA_HASH VARCHAR(64) NOT NULL,
    HWID VARCHAR(100),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'ATIVO'
);

CREATE GENERATOR GEN_USUARIOS_ID;
SET GENERATOR GEN_USUARIOS_ID TO 0;

SET TERM ^ ;
CREATE TRIGGER TRG_USUARIOS_BI FOR USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_USUARIOS_ID, 1);
END^
SET TERM ; ^

/* 2. TABELA DE LICENÇAS */
CREATE TABLE LICENCAS (
    ID INTEGER NOT NULL PRIMARY KEY,
    USUARIO_ID INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    TIPO_LICENCA VARCHAR(50) DEFAULT 'TRIAL_10_DIAS', -- 'TRIAL_10_DIAS', 'MENSAL', 'ANUAL', 'VITALICIA'
    DATA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_EXPIRACAO TIMESTAMP NOT NULL,
    STATUS_ATIVO SMALLINT DEFAULT 1
);

CREATE GENERATOR GEN_LICENCAS_ID;
SET GENERATOR GEN_LICENCAS_ID TO 0;

SET TERM ^ ;
CREATE TRIGGER TRG_LICENCAS_BI FOR LICENCAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_LICENCAS_ID, 1);
END^
SET TERM ; ^

/* 3. TABELA DE COMPROVANTES DE PAGAMENTO PIX */
CREATE TABLE COMPROVANTES_PAGAMENTO (
    ID INTEGER NOT NULL PRIMARY KEY,
    USUARIO_ID INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    DATA_ENVIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHAVE_PIX_USADA VARCHAR(100),
    VALOR_PAGO NUMERIC(15,2),
    COMPROVANTE_BLOB BLOB SUB_TYPE 0 SEGMENT SIZE 4096, -- Arquivo PDF/JPG em binário
    NOME_ARQUIVO VARCHAR(255),
    STATUS_ANALISE VARCHAR(30) DEFAULT 'AGUARDANDO_APROVACAO', -- 'AGUARDANDO_APROVACAO', 'APROVADO', 'REJEITADO'
    OBSERVACAO VARCHAR(255)
);

CREATE GENERATOR GEN_COMPROVANTES_ID;
SET GENERATOR GEN_COMPROVANTES_ID TO 0;

SET TERM ^ ;
CREATE TRIGGER TRG_COMPROVANTES_BI FOR COMPROVANTES_PAGAMENTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_COMPROVANTES_ID, 1);
END^
SET TERM ; ^

/* 4. ÍNDICES DE DESEMPENHO */
CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(EMAIL);
CREATE INDEX IDX_LICENCAS_USUARIO ON LICENCAS(USUARIO_ID, STATUS_ATIVO);
CREATE INDEX IDX_COMPROVANTES_USUARIO ON COMPROVANTES_PAGAMENTO(USUARIO_ID);

/* ============================================================================ */


